version: "3.7"
services:
  pg1:
    container_name: pg1
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - pg1_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
volumes:
  pg1_data:
