name: multi-container
on:
  push:
    branches:
      - develop
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |-
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t walosha/food_court -f ./client/Dockerfile .
      # - name: Generate deployment package
      #   run: zip -r deploy.zip . -x '*.git*'

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: application
          environment_name: Application-env
          existing_bucket_name: ${{ secrets.AWS_BUCKET_NAME }} # CHECK EXISTING BUCKET
          region: us-east-1
          version_label: ${{ github.sha }}
          deployment_package: docker-compose.yml
